M48
; DRILL file {KiCad 9.0.7} date 2026-04-22T20:24:32-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-22T20:24:32-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X164.895Y-103.1
X164.895Y-108.88
T2
X77.79Y-54.83
X77.79Y-143.83
X124.79Y-54.83
X165.79Y-142.83
M30
